export const USER_DETAILS_REQUEST = "USER.DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER.DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER.DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER.DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER.UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER.UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER.UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER.UPDATE_PROFILE_RESET";
