export const USER_REGISTER_REQUEST = "USER.REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER.REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER.REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER.LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER.LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER.LOGIN_FAIL";
export const USER_LOGOUT = "USER.LOGOUT";
