export const USER_REGISTER_REQUEST = "USER.REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER.REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER.REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER.REGISTER_RESET";


export const USER_LOGIN_REQUEST = "USER.LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER.LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER.LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER.LOGIN_RESET";
export const USER_LOGOUT = "USER.LOGOUT";

export const USER_DETAILS_REQUEST = "USER.DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER.DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER.DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER.DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER.UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER.UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER.UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER.UPDATE_PROFILE_RESET";

export const USER_GOOGLE_LOGIN_REQUEST = "USER.GOOGLE_LOGIN_REQUEST";
export const USER_GOOGLE_LOGIN_SUCCESS = "USER.GOOGLE_LOGIN_SUCCESS";
export const USER_GOOGLE_LOGIN_FAIL = "USER.GOOGLE_LOGIN_FAIL";
